before_script:
  - apt-get update -qy
#  - apt-get install -y cmake python3-pip
#  - pip3 install --upgrade pip
#  - apt-get install -y python3-pip
#  - pip3 install scikit-build
  - apt-get install -y python3-pip
  - pip3 install --upgrade cmake

supernu:
  script:
  - export code_dir=`pwd`
  - cd ${code_dir}/..
  - mkdir -p bin
  - cd bin
  - cmake $code_dir
  - make
